version: "3.9"

# a network between all the containers
# you can name your network whatever you want
networks:
  next-net:

services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - next-net
    volumes:
      - ./db:/var/lib/mongodb
    restart: unless-stopped
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    networks:
      - next-net
    volumes:
      - ./app:/app/nextjs
    depends_on:
      - mongodb
    environment:
      - SECRET_KEY_BASE=secret
      - MONGO_URL=mongodb://mongo:27017/mydb

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    networks:
      - next-net
    depends_on:
      - app
    ports:
      - 80:80
    links:
      - app
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs/nginx:/var/log/nginx
